#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Contracts\EventDispatcher\Event;

if (php_sapi_name() !== 'cli') {
    echo 'This script run only from the command line'.PHP_EOL;
    exit(255);
}

try {
    require __DIR__.'/app/common.php';

    $input = new ArgvInput();

    if (! in_array($input->getFirstArgument(), ['db:migrate', 'db:version'])) {
        $container['dispatcher']->dispatch(new Event, 'app.bootstrap');
    }

    $container['cli']->run($input);
} catch (Exception $e) {
    echo $e->getMessage().PHP_EOL;
    exit(255);
}
