#!/usr/bin/env php
<?php

require __DIR__.'/app/common.php';

use Symfony\Component\Console\Application;

$application = new Application('Kanboard', APP_VERSION);
$application->add(new Console\OverdueNotification($container));
$application->add(new Console\TaskExport($container));
$application->run();
