#!/bin/bash

VERSION=master

if [ "$SOURCE_BRANCH" != "" ]; then
    VERSION=$SOURCE_BRANCH

    if [ "$SOURCE_BRANCH" == "latest" ]; then
        VERSION=master
    fi
fi

echo "Building $VERSION"

docker build --build-arg VERSION=$VERSION -t $IMAGE_NAME .
